# This route enhancer config is not final
# But you can simply include it in your site configuration:
# imports:
#  - { resource: "EXT:blog/Configuration/Routes/Default.yaml" }
imports:
  - { resource: "EXT:blog/Configuration/Routes/BlogCategory.yaml" }
  - { resource: "EXT:blog/Configuration/Routes/BlogTag.yaml" }
  - { resource: "EXT:blog/Configuration/Routes/BlogArchive.yaml" }
  - { resource: "EXT:blog/Configuration/Routes/BlogAuthorPosts.yaml" }
  - { resource: "EXT:blog/Configuration/Routes/BlogFeedWidget.yaml" }
