services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    T3G\AgencyPack\Blog\Domain\Repository\:
        resource: '../Classes/Domain/Repository/*'

    T3G\AgencyPack\Blog\Service\:
        resource: '../Classes/Service/*'

    T3G\AgencyPack\Blog\Service\Avatar\AvatarResourceResolverInterface:
        class: T3G\AgencyPack\Blog\Service\Avatar\Gravatar\GravatarResourceResolver

    T3G\AgencyPack\Blog\Service\Avatar\Gravatar\GravatarUriBuilderInterface:
        class: T3G\AgencyPack\Blog\Service\Avatar\Gravatar\GravatarUriBuilder

    T3G\AgencyPack\Blog\AvatarProvider\GravatarProvider:
        public: true

    T3G\AgencyPack\Blog\Controller\CommentController:
        arguments:
            $avatarProvider: '@T3G\AgencyPack\Blog\AvatarProvider\GravatarProvider'
