services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  T3G\AgencyPack\Blog\:
    resource: '../Classes/*'

  T3G\AgencyPack\Blog\Domain\Factory\CommentFormFactory:
    public: true

  T3G\AgencyPack\Blog\Listener\RenderAdditionalContentToRecordList:
    tags:
      - name: event.listener
        identifier: 't3g/blog/render-additional-content-to-record-list'

  T3G\AgencyPack\Blog\Listener\ModifyPageLayoutContent:
    tags:
      - name: event.listener
        identifier: 't3g/blog/modify-page-module-content'

  T3G\AgencyPack\Blog\Mail\MailContent:
    public: true

  T3G\AgencyPack\Blog\Service\CacheService:
    public: true

  T3G\AgencyPack\Blog\Service\CommentService:
    public: true

  T3G\AgencyPack\Blog\Service\SetupService:
    public: true
