services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    T3G\AgencyPack\Blog\:
        resource: '../Classes/*'

    T3G\AgencyPack\Blog\AvatarProvider\AvatarResourceResolverInterface:
        class: T3G\AgencyPack\Blog\AvatarProvider\GravatarResourceResolver

    T3G\AgencyPack\Blog\AvatarProvider\GravatarUriBuilderInterface:
        class: T3G\AgencyPack\Blog\AvatarProvider\GravatarUriBuilder

    T3G\AgencyPack\Blog\AvatarProvider\GravatarProvider:
        public: true

    T3G\AgencyPack\Blog\Controller\CommentController:
        arguments:
            $avatarProvider: '@T3G\AgencyPack\Blog\AvatarProvider\GravatarProvider'
